import { HeroBlock, HeroBlockComponent } from "../blocks/marketing/HeroBlock";
import { ImageTextBlock, ImageTextBlockComponent } from "../blocks/content/ImageTextBlock";
import { RichTextBlock, RichTextBlockComponent } from "../blocks/content/RichTextBlock";
import { TestimonialsBlock, TestimonialsBlockComponent } from "../blocks/marketing/TestimonialsBlock";
import { CategoryGridBlock, CategoryGridBlockComponent } from "../blocks/ecommerce/CategoryGridBlock";
import { ProductGridBlock, ProductGridBlockComponent } from "../blocks/ecommerce/ProductGridBlock";
import { AllProductsBlock, AllProductsComponent } from "../blocks/ecommerce/AllProductsBlock";
import { CustomHtmlBlock, CustomHtmlBlockComponent } from "../blocks/content/CustomHtmlBlock";
import { PromoBannerBlock, PromoBannerComponent } from "../blocks/marketing/PromoBannerBlock";
import { AddToCartBlock, AddToCartComponent } from "../blocks/ecommerce/AddToCartBlock";
import { HeaderBlock, HeaderComponent } from "../blocks/navigation/HeaderBlock";
import { FooterBlock, FooterComponent } from "../blocks/footer/FooterBlock";
import { ProductSliderBlock, ProductSliderComponent } from "../blocks/ecommerce/ProductSliderBlock";
import { FeaturedProductBlock, FeaturedProductComponent } from "../blocks/ecommerce/FeaturedProductBlock";
import { NewsletterBlock, NewsletterComponent } from "../blocks/marketing/NewsletterBlock";
import { FaqBlock, FaqComponent } from "../blocks/content/FaqBlock";
import { ContactBlock, ContactComponent } from "../blocks/forms/ContactBlock";
import { FormBlock, FormComponent } from "../blocks/forms/FormBlock";
import { IconBoxBlock, IconBoxComponent } from "../blocks/content/IconBoxBlock";
import { CounterBlock, CounterComponent } from "../blocks/content/CounterBlock";
import { SocialIconsBlock, SocialIconsComponent } from "../blocks/content/SocialIconsBlock";
import { TabsBlock, TabsComponent } from "../blocks/content/TabsBlock";
import { AccordionBlock, AccordionComponent } from "../blocks/content/AccordionBlock";
import { CarouselBlock, CarouselComponent } from "../blocks/content/CarouselBlock";
import { ContainerBlock, ContainerComponent } from "../blocks/layout/ContainerBlock";
import { SectionBlock, SectionComponent } from "../blocks/layout/SectionBlock";
import { GridBlock, GridComponent } from "../blocks/layout/GridBlock";
import { ColumnsBlock, ColumnsComponent } from "../blocks/layout/ColumnsBlock";
import { StackBlock, StackComponent } from "../blocks/layout/StackBlock";
import { StockIndicatorBlock, StockIndicatorComponent } from "../blocks/ecommerce/StockIndicatorBlock";
import { TrustBadgesBlock, TrustBadgesComponent } from "../blocks/ecommerce/TrustBadgesBlock";
import { SalesCountdownBlock, SalesCountdownComponent } from "../blocks/marketing/SalesCountdownBlock";
import { StickyAddToCartBlock, StickyAddToCartComponent } from "../blocks/ecommerce/StickyAddToCartBlock";
import { RelatedProductsBlock, RelatedProductsComponent } from "../blocks/ecommerce/RelatedProductsBlock";
import { RecentlyViewedBlock, RecentlyViewedComponent } from "../blocks/ecommerce/RecentlyViewedBlock";
import { HeadingBlock, HeadingComponent } from "../blocks/content/HeadingBlock";
import { ButtonBlock, ButtonComponent } from "../blocks/content/ButtonBlock";
import { ImageBlock, ImageComponent } from "../blocks/content/ImageBlock";
import { IconBlock, IconComponent } from "../blocks/content/IconBlock";
import { DividerBlock, DividerComponent } from "../blocks/content/DividerBlock";
import { SpacerBlock, SpacerComponent } from "../blocks/content/SpacerBlock";
import { TextBlock, TextComponent } from "../blocks/content/TextBlock";
import { VideoBlock, VideoComponent } from "../blocks/content/VideoBlock";
import { MenuAnchorBlock, MenuAnchorComponent } from "../blocks/content/MenuAnchorBlock";
import { StarRatingBlock, StarRatingComponent } from "../blocks/content/StarRatingBlock";
import { AlertBlock, AlertComponent } from "../blocks/content/AlertBlock";
import { IconListBlock, IconListComponent } from "../blocks/content/IconListBlock";
import { ProgressBarBlock, ProgressBarComponent } from "../blocks/content/ProgressBarBlock";
import { ImageGalleryBlock, ImageGalleryComponent } from "../blocks/content/ImageGalleryBlock";
import { GoogleMapsBlock, GoogleMapsComponent } from "../blocks/content/GoogleMapsBlock";
import { ProductTitleBlock, ProductTitleComponent } from "../blocks/ecommerce/ProductTitleBlock";
import { ProductImagesBlock, ProductImagesComponent } from "../blocks/ecommerce/ProductImagesBlock";
import { ProductPriceBlock, ProductPriceComponent } from "../blocks/ecommerce/ProductPriceBlock";
import { ProductRatingBlock, ProductRatingComponent } from "../blocks/ecommerce/ProductRatingBlock";
import { ProductMetaBlock, ProductMetaComponent } from "../blocks/ecommerce/ProductMetaBlock";
import { ProductContentBlock, ProductContentComponent } from "../blocks/ecommerce/ProductContentBlock";
import { ProductShortDescriptionBlock, ProductShortDescriptionComponent } from "../blocks/ecommerce/ProductShortDescriptionBlock";
import { ProductAdditionalInfoBlock, ProductAdditionalInfoComponent } from "../blocks/ecommerce/ProductAdditionalInfoBlock";
import { ProductTabsBlock, ProductTabsComponent } from "../blocks/ecommerce/ProductTabsBlock";
import { ProductBreadcrumbsBlock, ProductBreadcrumbsComponent } from "../blocks/ecommerce/ProductBreadcrumbsBlock";
import { MiniCartBlock, MiniCartComponent } from "../blocks/ecommerce/MiniCartBlock";
import { CartPageBlock, CartPageComponent } from "../blocks/ecommerce/CartPageBlock";
import { WishlistButtonBlock, WishlistButtonComponent } from "../blocks/ecommerce/WishlistButtonBlock";
import { WishlistPageBlock, WishlistPageComponent } from "../blocks/ecommerce/WishlistPageBlock";
import { ProductFilterBlock, ProductFilterComponent } from "../blocks/ecommerce/ProductFilterBlock";
import { ProductQuickViewBlock, ProductQuickViewComponent } from "../blocks/ecommerce/ProductQuickViewBlock";
import { FlipBoxBlock, FlipBoxComponent } from "../blocks/content/FlipBoxBlock";
import { AnimatedHeadlineBlock, AnimatedHeadlineComponent } from "../blocks/content/AnimatedHeadlineBlock";
import { HotspotBlock, HotspotComponent } from "../blocks/content/HotspotBlock";
import { SliderProBlock, SliderProComponent } from "../blocks/content/SliderProBlock";

export default function registerBlocks(editor, opts = {}) {
  const bm = editor.BlockManager;
  const cm = editor.Components;

  // Helper to cleanly register a block and its component
  const register = (type, blockDef, compDef) => {
    if (compDef) cm.addType(`${type}-component`, compDef);
    if (blockDef) bm.add(`${type}-block`, blockDef);
  };

  register("hero", HeroBlock, HeroBlockComponent);
  register("image-text", ImageTextBlock, ImageTextBlockComponent);
  register("rich-text", RichTextBlock, RichTextBlockComponent);
  register("testimonials", TestimonialsBlock, TestimonialsBlockComponent);
  register("category-grid", CategoryGridBlock, CategoryGridBlockComponent);
  register("product-grid", ProductGridBlock, ProductGridBlockComponent);
  register("all-products", AllProductsBlock, AllProductsComponent);
  register("custom-html", CustomHtmlBlock, CustomHtmlBlockComponent);
  register("promo-banner", PromoBannerBlock, PromoBannerComponent);
  register("add-to-cart", AddToCartBlock, AddToCartComponent);
  register("header", HeaderBlock, HeaderComponent);
  register("footer", FooterBlock, FooterComponent);
  register("product-slider", ProductSliderBlock, ProductSliderComponent);
  register("featured-product", FeaturedProductBlock, FeaturedProductComponent);
  register("newsletter", NewsletterBlock, NewsletterComponent);
  register("faq", FaqBlock, FaqComponent);
  register("contact", ContactBlock, ContactComponent);
  register("form", FormBlock, FormComponent);
  register("container", ContainerBlock, ContainerComponent);
  register("section", SectionBlock, SectionComponent);
  register("grid", GridBlock, GridComponent);
  register("columns", ColumnsBlock, ColumnsComponent);
  register("stack", StackBlock, StackComponent);
  register("icon-box", IconBoxBlock, IconBoxComponent);
  register("counter", CounterBlock, CounterComponent);
  register("social-icons", SocialIconsBlock, SocialIconsComponent);
  register("tabs", TabsBlock, TabsComponent);
  register("accordion", AccordionBlock, AccordionComponent);
  register("carousel-pro", CarouselBlock, CarouselComponent);
  register("heading", HeadingBlock, HeadingComponent);
  register("button", ButtonBlock, ButtonComponent);
  register("image", ImageBlock, ImageComponent);
  register("icon", IconBlock, IconComponent);
  register("divider", DividerBlock, DividerComponent);
  register("spacer", SpacerBlock, SpacerComponent);
  register("text", TextBlock, TextComponent);
  register("video", VideoBlock, VideoComponent);
  register("stock-indicator", StockIndicatorBlock, StockIndicatorComponent);
  register("trust-badges", TrustBadgesBlock, TrustBadgesComponent);
  register("sales-countdown", SalesCountdownBlock, SalesCountdownComponent);
  register("sticky-add-to-cart", StickyAddToCartBlock, StickyAddToCartComponent);
  register("related-products", RelatedProductsBlock, RelatedProductsComponent);
  register("recently-viewed", RecentlyViewedBlock, RecentlyViewedComponent);
  register("menu-anchor", MenuAnchorBlock, MenuAnchorComponent);
  register("star-rating", StarRatingBlock, StarRatingComponent);
  register("alert", AlertBlock, AlertComponent);
  register("icon-list", IconListBlock, IconListComponent);
  register("progress-bar", ProgressBarBlock, ProgressBarComponent);
  register("image-gallery", ImageGalleryBlock, ImageGalleryComponent);
  register("google-maps", GoogleMapsBlock, GoogleMapsComponent);
  register("product-title", ProductTitleBlock, ProductTitleComponent);
  register("product-images", ProductImagesBlock, ProductImagesComponent);
  register("product-price", ProductPriceBlock, ProductPriceComponent);
  register("product-rating", ProductRatingBlock, ProductRatingComponent);
  register("product-meta", ProductMetaBlock, ProductMetaComponent);
  register("product-content", ProductContentBlock, ProductContentComponent);
  register("product-short-description", ProductShortDescriptionBlock, ProductShortDescriptionComponent);
  register("product-additional-info", ProductAdditionalInfoBlock, ProductAdditionalInfoComponent);
  register("product-tabs", ProductTabsBlock, ProductTabsComponent);
  register("product-breadcrumbs", ProductBreadcrumbsBlock, ProductBreadcrumbsComponent);
  register("mini-cart", MiniCartBlock, MiniCartComponent);
  register("cart-page", CartPageBlock, CartPageComponent);
  register("wishlist-button", WishlistButtonBlock, WishlistButtonComponent);
  register("wishlist-page", WishlistPageBlock, WishlistPageComponent);
  register("product-filter", ProductFilterBlock, ProductFilterComponent);
  register("product-quick-view", ProductQuickViewBlock, ProductQuickViewComponent);
  register("flip-box", FlipBoxBlock, FlipBoxComponent);
  register("animated-headline", AnimatedHeadlineBlock, AnimatedHeadlineComponent);
  register("hotspot", HotspotBlock, HotspotComponent);
  register("slider-pro", SliderProBlock, SliderProComponent);
}
