import {
  FiPlus,
  FiEdit,
  FiEdit2,
  FiTrash2,
  FiEye,
  FiDownload,
  FiUpload,
  FiRefreshCw,
  FiSettings,
  FiCheck,
  FiX,
  FiMoreVertical,
  FiMoreHorizontal,
  FiSave,
  FiCopy,
  FiSearch,
  FiAlertTriangle,
  FiAlertCircle,
  FiInfo,
  FiArrowLeft,
  FiArrowRight,
  FiArrowUp,
  FiArrowDown,
  FiChevronDown,
  FiChevronUp,
  FiChevronLeft,
  FiChevronRight,
  FiUser,
  FiUsers,
  FiUserPlus,
  FiUserCheck,
  FiUserX,
  FiShield,
  FiShieldOff,
  FiLock,
  FiUnlock,
  FiGrid,
  FiList,
  FiFilter,
  FiCalendar,
  FiClock,
  FiMail,
  FiSend,
  FiInbox,
  FiFile,
  FiFileText,
  FiFolder,
  FiImage,
  FiVideo,
  FiMusic,
  FiPackage,
  FiTruck,
  FiShoppingCart,
  FiShoppingBag,
  FiCreditCard,
  FiDollarSign,
  FiPercent,
  FiTag,
  FiBookmark,
  FiStar,
  FiHeart,
  FiHome,
  FiLogIn,
  FiLogOut,
  FiPower,
  FiPlayCircle,
  FiPauseCircle,
  FiStopCircle,
  FiToggleLeft,
  FiToggleRight,
  FiExternalLink,
  FiLink,
  FiPaperclip,
  FiPrinter,
  FiTrash,
  FiArchive,
  FiRotateCcw,
  FiRotateCw,
  FiZap,
  FiActivity,
  FiBarChart,
  FiPieChart,
  FiTrendingUp,
  FiTrendingDown,
  FiGlobe,
  FiCode,
  FiTerminal,
  FiServer,
  FiDatabase,
  FiCloud,
  FiWifi,
  FiBell,
  FiBellOff,
  FiVolume,
  FiVolumeX,
  FiCamera,
  FiMic,
  FiPhone,
  FiMessageSquare,
  FiMessageCircle,
  FiHelpCircle,
  FiBook,
  FiBookOpen,
  FiBookmark as FiBookmarkIcon,
  FiFlag,
  FiMapPin,
  FiNavigation,
  FiCompass,
  FiTarget,
  FiCrosshair,
  FiAward,
  FiGift,
  FiSun,
  FiMoon,
  FiCloud as FiCloudIcon,
  FiWind,
  FiDroplet,
} from "react-icons/fi";

export const iconMap = {
  plus: FiPlus,
  edit: FiEdit,
  "edit-2": FiEdit2,
  trash: FiTrash2,
  delete: FiTrash2,
  view: FiEye,
  eye: FiEye,
  download: FiDownload,
  upload: FiUpload,
  refresh: FiRefreshCw,
  settings: FiSettings,
  check: FiCheck,
  close: FiX,
  x: FiX,
  "more-vertical": FiMoreVertical,
  "more-horizontal": FiMoreHorizontal,
  save: FiSave,
  copy: FiCopy,
  search: FiSearch,
  "alert-triangle": FiAlertTriangle,
  "alert-circle": FiAlertCircle,
  info: FiInfo,
  "arrow-left": FiArrowLeft,
  "arrow-right": FiArrowRight,
  "arrow-up": FiArrowUp,
  "arrow-down": FiArrowDown,
  "chevron-down": FiChevronDown,
  "chevron-up": FiChevronUp,
  "chevron-left": FiChevronLeft,
  "chevron-right": FiChevronRight,
  user: FiUser,
  users: FiUsers,
  "user-plus": FiUserPlus,
  "user-check": FiUserCheck,
  "user-x": FiUserX,
  shield: FiShield,
  "shield-off": FiShieldOff,
  lock: FiLock,
  unlock: FiUnlock,
  grid: FiGrid,
  list: FiList,
  filter: FiFilter,
  calendar: FiCalendar,
  clock: FiClock,
  mail: FiMail,
  send: FiSend,
  inbox: FiInbox,
  file: FiFile,
  "file-text": FiFileText,
  folder: FiFolder,
  image: FiImage,
  video: FiVideo,
  music: FiMusic,
  package: FiPackage,
  truck: FiTruck,
  "shopping-cart": FiShoppingCart,
  "shopping-bag": FiShoppingBag,
  "credit-card": FiCreditCard,
  dollar: FiDollarSign,
  percent: FiPercent,
  tag: FiTag,
  bookmark: FiBookmarkIcon,
  star: FiStar,
  heart: FiHeart,
  home: FiHome,
  login: FiLogIn,
  logout: FiLogOut,
  power: FiPower,
  "play-circle": FiPlayCircle,
  "pause-circle": FiPauseCircle,
  "stop-circle": FiStopCircle,
  "toggle-left": FiToggleLeft,
  "toggle-right": FiToggleRight,
  "external-link": FiExternalLink,
  link: FiLink,
  paperclip: FiPaperclip,
  printer: FiPrinter,
  archive: FiArchive,
  "rotate-ccw": FiRotateCcw,
  "rotate-cw": FiRotateCw,
  zap: FiZap,
  activity: FiActivity,
  "bar-chart": FiBarChart,
  "pie-chart": FiPieChart,
  "trending-up": FiTrendingUp,
  "trending-down": FiTrendingDown,
  globe: FiGlobe,
  code: FiCode,
  terminal: FiTerminal,
  server: FiServer,
  database: FiDatabase,
  cloud: FiCloudIcon,
  wifi: FiWifi,
  bell: FiBell,
  "bell-off": FiBellOff,
  volume: FiVolume,
  "volume-x": FiVolumeX,
  camera: FiCamera,
  mic: FiMic,
  phone: FiPhone,
  "message-square": FiMessageSquare,
  "message-circle": FiMessageCircle,
  "help-circle": FiHelpCircle,
  book: FiBook,
  "book-open": FiBookOpen,
  flag: FiFlag,
  "map-pin": FiMapPin,
  navigation: FiNavigation,
  compass: FiCompass,
  target: FiTarget,
  crosshair: FiCrosshair,
  award: FiAward,
  gift: FiGift,
  sun: FiSun,
  moon: FiMoon,
  wind: FiWind,
  droplet: FiDroplet,
};

export const resolveIcon = (name) => {
  if (!name) return null;
  if (typeof name !== "string") return name;
  return iconMap[name] || null;
};
