const platformCoupons = [
  {
    code: "WELCOME50",
    title: "Welcome 50% Off",
    description: "50% discount for new subscribers on their first subscription",
    discountType: "percentage",
    discountValue: 50,
    applicableTo: "subscription",
    status: "active",
    startDate: new Date("2026-01-01T00:00:00Z"),
    endDate: new Date("2027-12-31T23:59:59Z"),
    usageLimit: 1000,
    usageLimitPerCustomer: 1,
  },
  {
    code: "BLACKFRIDAY",
    title: "Black Friday Special",
    description: "Special Black Friday discount for annual subscriptions",
    discountType: "percentage",
    discountValue: 30,
    applicableTo: "subscription",
    status: "active",
    startDate: new Date("2026-11-24T00:00:00Z"),
    endDate: new Date("2026-11-30T23:59:59Z"),
    usageLimit: 5000,
    usageLimitPerCustomer: 1,
  },
  {
    code: "PARTNER20",
    title: "Partner 20% Off",
    description: "20% discount for partner store subscriptions",
    discountType: "percentage",
    discountValue: 20,
    applicableTo: "subscription",
    status: "active",
    startDate: new Date("2026-01-01T00:00:00Z"),
    endDate: new Date("2027-12-31T23:59:59Z"),
    usageLimit: 5000,
    usageLimitPerCustomer: 1,
  },
  {
    code: "LIFETIME",
    title: "Lifetime Access",
    description: "Lifetime access discount for one-time payment",
    discountType: "fixed",
    discountValue: 500,
    applicableTo: "subscription",
    status: "active",
    startDate: new Date("2026-01-01T00:00:00Z"),
    endDate: new Date("2027-12-31T23:59:59Z"),
    usageLimit: 100,
    usageLimitPerCustomer: 1,
  },
];

module.exports = platformCoupons;