export const GOOGLE_FONTS = [
  { value: "Inter", label: "Inter" },
  { value: "Roboto", label: "Roboto" },
  { value: "Open Sans", label: "Open Sans" },
  { value: "Lato", label: "Lato" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Poppins", label: "Poppins" },
  { value: "Raleway", label: "Raleway" },
  { value: "Oswald", label: "Oswald" },
  { value: "Noto Sans", label: "Noto Sans" },
  { value: "Nunito", label: "Nunito" },
  { value: "Ubuntu", label: "Ubuntu" },
  { value: "Merriweather", label: "Merriweather" },
  { value: "Playfair Display", label: "Playfair Display" },
  { value: "Lora", label: "Lora" },
  { value: "Fira Sans", label: "Fira Sans" },
  { value: "Work Sans", label: "Work Sans" },
  { value: "DM Sans", label: "DM Sans" },
  { value: "Outfit", label: "Outfit" },
  { value: "Space Grotesk", label: "Space Grotesk" },
  { value: "Plus Jakarta Sans", label: "Plus Jakarta Sans" },
  { value: "Manrope", label: "Manrope" },
  { value: "Urbanist", label: "Urbanist" },
  { value: "Sora", label: "Sora" },
  { value: "Figtree", label: "Figtree" },
  { value: "Quicksand", label: "Quicksand" },
  { value: "Titillium Web", label: "Titillium Web" },
  { value: "Josefin Sans", label: "Josefin Sans" },
  { value: "Karla", label: "Karla" },
  { value: "Rubik", label: "Rubik" },
  { value: "Cairo", label: "Cairo" },
  { value: "Catamaran", label: "Catamaran" },
  { value: "Assistant", label: "Assistant" },
  { value: "Heebo", label: "Heebo" },
  { value: "Lexend", label: "Lexend" },
  { value: "Epilogue", label: "Epilogue" },
];

export const SYSTEM_FONTS = [
  { value: "inherit", label: "Police du thème (par défaut)" },
  { value: "Arial, sans-serif", label: "Arial" },
  { value: "'Helvetica Neue', sans-serif", label: "Helvetica Neue" },
  { value: "Georgia, serif", label: "Georgia (Serif)" },
  { value: "'Times New Roman', serif", label: "Times New Roman" },
  { value: "'Courier New', monospace", label: "Courier New" },
  { value: "system-ui, sans-serif", label: "System UI" },
  { value: "Tahoma, sans-serif", label: "Tahoma" },
  { value: "Verdana, sans-serif", label: "Verdana" },
];

export const FONT_OPTIONS = [
  ...SYSTEM_FONTS,
  ...GOOGLE_FONTS.map(f => ({ ...f, label: `${f.label} (Google)` })),
];
